version: '3.8'
services:
  db:
    image: postgres:13.1-alpine
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=mystic
      - POSTGRES_DB=task_manager
      - PGDATA=/var/lib/postgresql/data/pgdata
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - backend
networks:
  backend:
volumes:
  db: